/**
 * apply_cloudinary_mapping.js
 * 
 * Reads cloudinary_mapping.json generated by map_cloudinary_to_db.js
 * and updates ONLY the images field for each product in MongoDB.
 * No other fields are touched.
 */

require('dotenv').config();
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');

async function main() {
  const mappingPath = path.join(__dirname, 'cloudinary_mapping.json');
  if (!fs.existsSync(mappingPath)) {
    console.error('cloudinary_mapping.json not found. Run map_cloudinary_to_db.js first.');
    process.exit(1);
  }

  const mapping = JSON.parse(fs.readFileSync(mappingPath, 'utf-8'));
  
  await mongoose.connect(process.env.MONGO_URI);
  const Jewellery = require('./models/Jewellery');

  let updatedCount = 0;
  let skippedCount = 0;
  let notFoundCount = 0;

  for (const entry of mapping) {
    if (!entry.proposedJewelId || !entry.urls || entry.urls.length === 0) {
      skippedCount++;
      continue;
    }

    const item = await Jewellery.findOne({
      jewelId: { $regex: new RegExp('^' + entry.proposedJewelId + '$', 'i') }
    });

    if (!item) {
      console.log('Not found in DB: ' + entry.proposedJewelId);
      notFoundCount++;
      continue;
    }

    // Skip if already has Cloudinary images (don't overwrite manually-set ones)
    const alreadyHasImages = item.images && item.images.some(img => img.url && img.url.includes('cloudinary.com'));
    if (alreadyHasImages && !entry.isAnchor) {
      // Re-seed even anchors to keep them clean
      skippedCount++;
      continue;
    }

    const newImages = entry.urls.map(url => ({ type: 'image', url }));

    await Jewellery.updateOne(
      { _id: item._id },
      { $set: { images: newImages } }
    );
    console.log('Updated ' + entry.proposedJewelId + ' -> ' + newImages.length + ' image(s)');
    updatedCount++;
  }

  console.log('\nDone! Updated: ' + updatedCount + ', Skipped: ' + skippedCount + ', Not found: ' + notFoundCount);
  mongoose.disconnect();
}

main().catch(console.error);
